AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SF AI API - OpenAI-compatible LLM proxy on AWS (single env, low cost)

Parameters:
  ProjectName:
    Type: String
    Default: sfai
    Description: Project name prefix
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, stg, prod]
  AllowedOrigins:
    Type: String
    Default: https://app.cursor.sh
    Description: Comma-separated origins for CORS (use * only for dev)
  ModelMapUrl:
    Type: String
    Default: https://example-bucket.s3.ap-northeast-1.amazonaws.com/config/model_map.json
    Description: Public HTTPS URL to model_map.json in S3
  RateLimitQpm:
    Type: Number
    Default: 60
    Description: Soft rate limit hint (primary control is API Gateway throttling)
  LogMaskPII:
    Type: String
    Default: 'true'
    AllowedValues: ['true','false']
  OpenAISecretArn:
    Type: String
    Description: Secrets Manager ARN for OPENAI_API_KEY (e.g. arn:aws:secretsmanager:..:secret:/sfai/prod/OPENAI_API_KEY-xxxx)
  AnthropicSecretArn:
    Type: String
    Description: Secrets Manager ARN for ANTHROPIC_API_KEY
  LogRetentionDays:
    Type: Number
    Default: 14

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 512
    Timeout: 60
    Tracing: PassThrough
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        ALLOW_ORIGINS: !Ref AllowedOrigins
        MODEL_MAP_URL: !Ref ModelMapUrl
        RATE_LIMIT_QPM: !Ref RateLimitQpm
        LOG_MASK_PII: !Ref LogMaskPII

Resources:
  LLMProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-llm-proxy"
      Description: OpenAI-compatible LLM proxy endpoint
      CodeUri: src/
      Handler: handler.lambdaHandler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource:
                - !Ref OpenAISecretArn
                - !Ref AnthropicSecretArn
      Environment:
        Variables:
          OPENAI_SECRET_ARN: !Ref OpenAISecretArn
          ANTHROPIC_SECRET_ARN: !Ref AnthropicSecretArn

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      ApiName: !Sub "${ProjectName}-${Environment}-api"
      CorsConfiguration:
        AllowOrigins: !Split [",", !Ref AllowedOrigins]
        AllowMethods: [POST, OPTIONS]
        AllowHeaders: ['*']

  ChatCompletionsRoute:
    Type: AWS::Serverless::FunctionUrl
    DeletionPolicy: Delete
    Metadata:
      Comment: Not used. Real integration via HttpApi + Integration below.
    Properties:
      AuthType: NONE
      FunctionName: !Ref LLMProxyFunction
    Condition: FalseCondition

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LLMProxyFunction.Arn
      PayloadFormatVersion: '2.0'

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: POST /chat/completions
      Target: !Sub integrations/${Integration}

  PermissionInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LLMProxyFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/POST/chat/completions

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ProjectName}-${Environment}-llm-proxy"
      RetentionInDays: !Ref LogRetentionDays

Outputs:
  HttpApiUrl:
    Description: Base URL of the HTTP API
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  ChatCompletionsUrl:
    Description: Chat Completions endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/chat/completions"

